
theme: jekyll-theme-slate
##jekyll-theme-cayman
title: Feray Ece Topcu Progress Journal
description: BDA 503 Fall 2017 - MEF University
<img src="test.png" width="669" height="400" alt="Cover image" />  
